### ISSUE TITLE
🔍 유저 도메인 백엔드 스택 확정

### ISSUE THREAD

**Issue by dev2820** [ganada-labs/nlog-BE#1]
> 기술 검증에 대한 산출물(기술 문서 등)는 comment로 링크를 추가해주세요.

## 설명
회원가입, 유저 조회를 위한 백엔드 환경을 구상하고 공유한다.

- [x] 유저 도메인을 위한 백엔드 기술 스택 확정하기
- [x] 유저 백엔드 아키텍처 생성 및 공유

**Comment by dev2820** [comment]
Webhook Test Comment

**Comment by dev2820** [comment]
웹훅 테스트 2

**Comment by dev2820** [comment]
유저 도메인, Auth를 위한 기술 스택 확정 및 아키텍처 구상

아래 문서 참고하고 피드백 주세요
@custardcream98 
https://www.notion.so/User-Auth-Domain-529ca690a3a34b14a0b90e6d36c7cd8c?pvs=4

**Comment by dev2820** [comment]
현재 Nginx + Certbot(인증서 생성) 을 Docker 환경에서 실행하는 것을 테스트 중

테스트 중 너무 많은 인증서 갱신 요청으로 인해 내일까지 벤이 된 상태

주말중에 트라이해보겠음

**Comment by dev2820** [comment]
@custardcream98 

현 테스크는 2일 이상 걸릴 것으로 예상되기 때문에 내부적으로 검증할 내용들은 다른 테스크로 쪼개겠습니다. 아키텍처 문서 검토 후 피드백 완료 되면 이 테스크가 완료되는 걸로 할게요

**Comment by custardcream98** [comment]
LGTM
